services:
  guacd:
    image: guacamole/guacd:1.5.0
    restart: unless-stopped
    ports:
      - "4822:4822"
    environment:
      - GUACD_LOG_LEVEL=debug

  server:
    image: ghcr.io/atvriders/rdp-in-browser-server:master
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - GUACD_HOST=guacd
      - GUACD_PORT=4822
      - PORT=3001
    depends_on:
      - guacd

  frontend:
    image: ghcr.io/atvriders/rdp-in-browser-frontend:master
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - server

  rdp-server:
    build:
      context: ./test-rdp
    container_name: test-rdp
    restart: unless-stopped
    environment:
      RDP_USERNAME: testuser
      RDP_PASSWORD: testpass
      TZ: Asia/Kolkata
    ports:
      - "3389:3389"
    shm_size: "1gb"
